# Generated by Django 3.0.3 on 2020-04-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='bookid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.BookDetails'),
        ),
    ]
