# Generated by Django 3.0.3 on 2020-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200405_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='bookid',
            field=models.IntegerField(),
        ),
    ]
